version = 0.1

[default.deploy.parameters]
stack_name = "smart-job-tracker"
resolve_s3 = true
s3_prefix = "smart-job-tracker"
parameter_overrides = "CognitoUserPoolId=us-east-1_dPowTiOVG SNSTopicArn=arn:aws:sns:us-east-1:862433051237:job-tracker-reminders"
region = "us-east-1"
profile = "job-tracker"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
