AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Job Application Tracker - Lambda function

Globals:
  Function:
    Timeout: 15
    MemorySize: 256

Parameters:
  CognitoUserPoolId:
    Type: String
    Description: The Cognito User Pool ID used to authorize API requests

Resources:
  JobTrackerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"

  JobTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.main.handler
      Runtime: python3.12
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: JobApplications
          S3_RESUME_BUCKET_NAME: smart-job-tracker-resumes-shankar2026
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref JobTrackerApi
            Path: /{proxy+}
            Method: ANY
        HealthCheckEvent:
          Type: Api
          Properties:
            RestApiId: !Ref JobTrackerApi
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${JobTrackerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"